const ShopActionTypes = {
    FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
    FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
    FETCH_COLLECTION_FAILUR: 'FETCH_COLLECTION_FAILUR'
}

export default ShopActionTypes;